[project]
name = 'suprow_contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.anonymization]
path = 'contracts/anonymization.clar'
clarity_version = 2
epoch = 2.5

[contracts.community_governance]
path = 'contracts/community_governance.clar'
clarity_version = 2
epoch = 2.5

[contracts.decentralized_identity]
path = 'contracts/decentralized_identity.clar'
clarity_version = 2
epoch = 2.5

[contracts.privacy]
path = 'contracts/privacy.clar'
clarity_version = 2
epoch = 2.5

[contracts.research]
path = 'contracts/research.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
